fix: Check referenced file relative to processed file or working directory

diff --git a/src/inline-patch b/src/inline-patch
--- a/src/inline-patch
+++ b/src/inline-patch
@@ -59,6 +59,17 @@ process() {
         ref_file="$(echo "${line}" | cut -d':' -f3 -)"
         end="$(grep -n "${indentation}${comment} end-file:${ref_file}" "${p_file}" | head -n 1 | cut -d':' -f1 -)"
 
+        # Check referenced file relative to processed file and relative to CWD
+        rel_ref_file="$(dirname "${p_file}")/${ref_file}"
+        rel_ref_file="$(realpath "${rel_ref_file}" 2>/dev/null || true)"
+        if [ ! -f "${rel_ref_file}" ]; then
+            rel_ref_file="$(realpath "${PWD}/${ref_file}" 2>/dev/null || true)"
+        fi
+        if [ ! -f "${rel_ref_file}" ]; then
+            echo "Referenced file: ${ref_file} not found."
+            exit 1
+        fi
+        ref_file="${rel_ref_file}"
         patch_file "${p_file}" "${ref_file}" "${start}" "${end}" "${indentation}"
     done
 }
